global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    

  # For direct metrics collection from service to Prometheus
  # - job_name: 'cloudserver-service-app'
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ['host.docker.internal:8002']
