---
name: release
run-name: release ${{ inputs.tag }}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to be released'
        required: true

jobs:
  build-federation-image:
    uses: scality/workflows/.github/workflows/docker-build.yaml@v2
    secrets: inherit
    with:
      push: true
      registry: ghcr.io
      namespace: scality
      name: ${{ github.event.repository.name }}
      context: .
      file: images/svc-base/Dockerfile
      tag: ${{ github.event.inputs.tag }}-svc-base

  build-image:
    uses: scality/workflows/.github/workflows/docker-build.yaml@v2
    secrets: inherit
    with:
      push: true
      registry: ghcr.io
      namespace: scality
      name: ${{ github.event.repository.name }}
      context: .
      file: Dockerfile
      tag: ${{ github.event.inputs.tag }}

  github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          name: Release ${{ github.event.inputs.tag }}
          tag_name: ${{ github.event.inputs.tag }}
          generate_release_notes: true
          target_commitish: ${{ github.sha }}
